[project]
name = "backend"
version = "0.1.0"
dependencies = ["dotenv", "pandas", "requests", "coloredlogs"]

[project.optional-dependencies]
dev = ["matplotlib", "ruff"]

[project.scripts]
main = "main:main"

[tool.ruff]
line-length = 100

[tool.ruff.format]
indent-style = "tab"

[tool.ruff.lint]
extend-select = ["ANN", "I", "RSE"]
