[project]
name = "wendify"
version = "0.1.0"
dependencies = ["coloredlogs", "dotenv", "pandas", "plotly", "requests"]

[project.optional-dependencies]
dev = ["ruff"]

[project.scripts]
wendify = "main:main"

[tool.ruff]
line-length = 100

[tool.ruff.format]
indent-style = "tab"

[tool.ruff.lint]
extend-select = ["ANN", "I", "PD", "RET", "RSE"]
